### PR TITLE
master-vw-448

### PR DESCRIPTION
**Pull request by vicnate5**
Hey Java, This pulls causes a partial regression of https://issues.liferay.com/browse/LPS-64305. We have a poshi test that tries to adds invalid characters to the Field Name field. The test asserts the invalid characters are not saved and are set back to the default field name. It looks like the name is set back to the default field name, but the user can no longer see the real field name until after they save the field. Can you take another look at this? Thanks!

cc @brunobasto

### CODE REVIEW

**Comment by vicnate5** [comment]
screenshot 2016-07-08 16 24 12

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by vicnate5** [comment]
I noticed @brunobasto merged this under LPS-66476. Closing this pull. I need to send the test fixes in.

**Pull request closed without merging**
