### PR TITLE
[TECHNICAL SUPPORT] LPS-67761 Navigation bar and breadcrumb don't work properly on Link To Page field's Select Page panel

### PR DESCRIPTION
**Pull request by zsagia**
Hi Thiago,

Firstly, I'd like to say that the new Link To Page feature is very cool we should use it on Product Menu as well. Furthermore, before I released it to customer I did some test on it. I found a little mistake when we have more than one page level and we navigate between Private and Public pages.
Please check my attached screen on LPS-67761.
I'd like to ask you for a first review.

Thanks in advance,
 Zsaga

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by thiago-rocha** [comment]
@zsagia The code looks good to me, can I send it to Bruno Basto?

**Comment by zsagia** [comment]
Hi Thiago,

Yes, please send it.

Thanks in advance,

Zsolt Szabo a.k.a. Zsaga

Engineer, Technical Support

Subscription Services | EMEA

Liferay Hungary | Madarász Viktor u. 47., 1138, Budapest, Hungary

**Comment by thiago-rocha** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/717. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
